<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <!-- Required for IHttpContextAccessor and other ASP.NET Core types when used in class library -->
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SafePharma.DAL\SafePharma.DAL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Mappings\Profiles\" />
  </ItemGroup>

</Project>